# Sample usage of desired packages

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Values
v = 3.0  # m/s
g = 0.2  # decimal grade
t = 3600  # seconds
v_array = v * (1 + np.sin(np.linspace(0, 2*np.pi, 100)))
g_array = g * np.sin(np.linspace(0, 2*np.pi, 100))

## Existing and proposed low-level API

### Minetti

In [3]:
from specialsauce.sources import minetti

In [4]:
# cost_of_walking is analogous
minetti.cost_of_running(g)  # -> J/kg/m

9.006688

In [5]:
minetti.cost_of_running(g_array)

array([3.6       , 3.85471402, 4.12267645, 4.40201285, 4.6906614 ,
       4.98641216, 5.28694665, 5.58987612, 5.89277755, 6.1932263 ,
       6.48882496, 6.7772283 , 7.05616441, 7.32345233, 7.57701696,
       7.81490168, 8.03527942, 8.23646278, 8.41691363, 8.57525236,
       8.71026708, 8.82092234, 8.90636752, 8.9659442 , 8.99919236,
       9.00585488, 8.98588021, 8.93942289, 8.86684192, 8.76869723,
       8.64574418, 8.49892679, 8.32936982, 8.13837014, 7.92738777,
       7.69803666, 7.45207526, 7.19139672, 6.91801839, 6.63406998,
       6.34177996, 6.0434593 , 5.7414822 , 5.43826304, 5.13622953,
       4.83779182, 4.54530822, 4.26104783, 3.98715149, 3.72559217,
       3.47813641, 3.24630862, 3.03135984, 2.83424266, 2.65559376,
       2.49572501, 2.3546239 , 2.23196352, 2.1271216 , 2.03920812,
       1.96710002, 1.90948166, 1.8648892 , 1.83175706, 1.80846463,
       1.79338151, 1.78490986, 1.78152279, 1.7817979 , 1.78444571,
       1.78833293, 1.79250075, 1.79617872, 1.79879472, 1.79998

### Strava

In [6]:
from specialsauce.sources import strava

In [7]:
# TODO: This currently returns a scalar ndarray, when a scalar is desired.
strava.gap_speed_factor(g)

array(2.297)

In [8]:
strava.gap_speed(v, g)  # decimal grade and m/s only

6.891

In [9]:
strava.gap_speed_factor(g_array)

array([1.        , 1.03488316, 1.07627396, 1.126401  , 1.18256763,
       1.24111646, 1.30611208, 1.37334979, 1.44216002, 1.52191199,
       1.60282147, 1.68003522, 1.75324231, 1.82214797, 1.89316822,
       1.96249502, 2.02590468, 2.08314187, 2.13397612, 2.17820274,
       2.21564364, 2.24614807, 2.26959319, 2.28588459, 2.29495668,
       2.29677293, 2.29132602, 2.27863788, 2.25875961, 2.23177125,
       2.19778148, 2.15692715, 2.10937277, 2.05530983, 1.99495602,
       1.92855436, 1.85637223, 1.78825058, 1.71715841, 1.64191011,
       1.56280867, 1.4801726 , 1.40803636, 1.33813525, 1.27380196,
       1.21101128, 1.1538888 , 1.10140112, 1.05228082, 1.01745036,
       0.98730883, 0.96197758, 0.93563941, 0.91251616, 0.89593221,
       0.88469698, 0.876     , 0.876     , 0.87955612, 0.89343556,
       0.90672134, 0.91935994, 0.93130048, 0.94421976, 0.96662663,
       0.98723912, 1.00597423, 1.02275651, 1.0375184 , 1.05020046,
       1.06075161, 1.06912937, 1.07530001, 1.07923867, 1.08092

In [10]:
strava.gap_speed(v_array, g_array)

array([3.00000000e+00, 3.30155851e+00, 3.63756637e+00, 4.01872136e+00,
       4.43870132e+00, 4.88515890e+00, 5.37463470e+00, 5.89082564e+00,
       6.43000054e+00, 7.03415918e+00, 7.65944111e+00, 8.27982313e+00,
       8.88935409e+00, 9.48204826e+00, 1.00876321e+01, 1.06832888e+01,
       1.12421022e+01, 1.17580028e+01, 1.22253272e+01, 1.26388985e+01,
       1.29941002e+01, 1.32869422e+01, 1.35141185e+01, 1.36730539e+01,
       1.37619419e+01, 1.37797703e+01, 1.37263359e+01, 1.36022475e+01,
       1.34089171e+01, 1.31485394e+01, 1.28240603e+01, 1.24391345e+01,
       1.19980729e+01, 1.15057811e+01, 1.09676888e+01, 1.03896730e+01,
       9.77797427e+00, 9.18817902e+00, 8.58631923e+00, 7.97061480e+00,
       7.34704422e+00, 6.72151141e+00, 6.15970788e+00, 5.62390361e+00,
       5.12840365e+00, 4.65657774e+00, 4.22430795e+00, 3.82627209e+00,
       3.45691943e+00, 3.14919588e+00, 2.86795067e+00, 2.61160740e+00,
       2.36342124e+00, 2.13443771e+00, 1.93055681e+00, 1.74633837e+00,
      

### TrainingPeaks

In [11]:
from specialsauce.sources import trainingpeaks

In [12]:
trainingpeaks.ngp_speed_factor(g)

array(2.365)

In [13]:
from specialsauce.sources import trainingpeaks_next
trainingpeaks_next.ngp_speed(v, g)

7.095000000000001

In [14]:
trainingpeaks_next.training_stress_score(v_array, g_array, t)  # assumes 1-second samples
#                                        (x_array, y_array)  # assumes 1-second samples
#                                        (x_array, y_array, t_array)

/home/aaron/aaron-schroeder/specialsauce/env/lib/python3.8/site-packages/specialsauce/sources/trainingpeaks_next.py:53: RuntimeWarning: divide by zero encountered in true_divide
  return 100 * (ngp / ftp) ** 2 * (duration_sec / 3600)


array([           inf, 6.32541772e+06, 1.78197070e+06, 8.88489418e+05,
       5.58393659e+05, 3.97804816e+05, 3.06464121e+05, 2.49004659e+05,
       2.10237918e+05, 1.82712246e+05, 1.62401243e+05, 1.46963796e+05,
       1.34958082e+05, 1.25454142e+05, 1.17829139e+05, 1.11652808e+05,
       1.06620281e+05, 1.02511067e+05, 9.91631759e+04, 9.64563036e+04,
       9.43006707e+04, 9.26294765e+04, 9.13937496e+04, 9.05588410e+04,
       9.01020840e+04, 9.00113303e+04, 9.02841873e+04, 9.09278696e+04,
       9.19596486e+04, 9.34079496e+04, 9.53142260e+04, 9.77358365e+04,
       1.00750300e+05, 1.04461524e+05, 1.09008969e+05, 1.14581308e+05,
       1.21437226e+05, 1.29937870e+05, 1.40599102e+05, 1.54178751e+05,
       1.71828767e+05, 1.95374673e+05, 2.27862081e+05, 2.74711888e+05,
       3.46415422e+05, 4.65696824e+05, 6.90323593e+05, 1.20858955e+06,
       2.98604085e+06, 2.37919108e+07, 2.09552937e+07, 2.03923098e+06,
       6.38974332e+05, 2.81809307e+05, 1.46244926e+05, 8.32730258e+04,
      

In [15]:
import datetime

df = pd.DataFrame(dict(
  tss=[10, 0, 10, 0, 20, 20],
  recorded=[
    datetime.datetime(1989, 12, 4) + datetime.timedelta(days=i)
    # for i in [0, 1, 2, 3, 4, 5]
    for i in [0, 2, 4, 6, 8, 10]
  ]
))

In [16]:
trainingpeaks_next.calc_ctl_atl(df)
# df['CTL_post']
df

tss   recorded   ATL_pre   CTL_pre  ATL_post  CTL_post
0   10 1989-12-04  0.000000  0.000000  1.428571  0.238095
1    0 1989-12-06  1.049563  0.226892  1.049563  0.226892
2   10 1989-12-08  0.771107  0.216217  2.199679  0.454312
3    0 1989-12-10  1.616090  0.432935  1.616090  0.432935
4   20 1989-12-12  1.187332  0.412565  4.044475  0.888755
5   20 1989-12-14  2.971451  0.846938  5.828594  1.323128

In [17]:
# trainingpeaks.chronic_training_load(df['tss'], df['recorded']) - df['CTL_post']
trainingpeaks_next.chronic_training_load(df['tss']) - df['CTL_post']

TypeError: chronic_training_load() missing 1 required positional argument: 'day_arr'

In [18]:
# trainingpeaks.acute_training_load(df['tss'], df['recorded']) - df['ATL_post']
trainingpeaks_next.acute_training_load(df['tss']) - df['ATL_post']

TypeError: acute_training_load() missing 1 required positional argument: 'day_arr'

### Jones (2002)

Based on XXX

In [19]:
from specialsauce.sources import jones

In [20]:
# TODO: Fix this function!

n = 20
vo_2_ss_arr = [13.0 for _ in range(n)]
seconds_arr = [i for i in range(n)]

jones.aerobic_vo_2_timeseries(vo_2_ss_arr, seconds_arr, tau=20)

1.0


[13.0,
 13.0,
 13.0,
 13.0,
 13.0,
 13.0,
 13.0,
 13.0,
 13.0,
 13.0,
 13.0,
 13.0,
 13.0,
 13.0,
 13.0,
 13.0,
 13.0,
 13.0,
 13.0,
 13.0]

### Daniels Running Formula (DRF)

In [ ]:
from specialsauce.sources import daniels as drf

ImportError: cannot import name 'daniels' from 'specialsauce.sources' (/home/aaron/aaron-schroeder/specialsauce/env/lib/python3.8/site-packages/specialsauce/sources/__init__.py)

#### Fundamental equations

Daniels Running Formula is based on just a couple of equations with some baked-in assumptions.

The first equation defines the oxygen consumption rate required to run at a particular velocity. It assumes that every runner consumes the same amount of oxygen at a given speed per kilogram of body mass.

In other words, this equation defines running economy: the amount of energy required to move at a particular speed.

Daniels originally published this equation in a book called "Oxygen Power" (verify!) which is now out of print. It was derived from laboratory measurements of the oxygen consumption of elite runners.

TODO: Research the background of this equation:
- What paper/book was it published in
- What was the experimental setup
- Who were the athletes tested

In [ ]:
v_mmin = v * 60  # meters/minute
t_min = t / 60  # minutes
d_m = v * t  # meters

In [ ]:
drf.oxygen_cost_v(v_mmin)  # mL/kg/min

31.57604

In [ ]:
drf.oxygen_cost(d_m, t_min)  # mL/kg/min

31.57604

The second equation describes the percentage of VO2max that is sustainable for a given period of activity. For shorter bouts, a given runner can maintain a higher percentage of VO2max.

Like the running economy equation, the intensity equation assumes all runners have the same profile.

In [ ]:
vo2_max_fraction = drf.drop_dead_intensity(t_min)
vo2_max_fraction

0.8880073144800814

#### Derived equations

The real utility of Daniels Running Formula comes from combining and manipulating the two fundamental equations.

In [ ]:
race_dist_m = 5000  # meters
vo2max = 50  # the given athlete's VO2max [mL/kg/min]

Calculate the speed that will result in VO2max oxygen consumption (vVO2max):

In [ ]:
drf.vdot_to_speed(vo2max)  # m/min

260.77202148708056

For a given race distance, predict the finishing time of a runner with a given VO2max:

In [ ]:
predicted_finish_time_min = drf.predict_time(race_dist_m, vo2max)  # minutes
predicted_finish_time_min

19.93368040546417

For a given race distance and finish time, predict the VO2max of the athlete 
(note: this VO2max should be the exact value we assigned above, since we're round-tripping).

In [ ]:
drf.predict_vo2max(race_dist_m, predicted_finish_time_min)

50.00000000000013

## Core API functions (with proposed updates)

In [22]:
import math
from specialsauce import core

n_t = 60 * 60 * 3  # 3 hours in seconds
time_series = pd.Series(range(n_t))
speed = 3.0
speed_series = pd.Series([3.0 + math.sin(0.1 * t) for t in time_series])
grade_series = pd.Series([-4.0 + math.sin(0.1 * t) for t in time_series])

In [ ]:

# core.cost_of_wind_running(speed)
# core.cost_of_inclined_treadmill_running(grade)
c_r = core.run_cost(speed, grade=0.0)
p = core.run_power(speed, grade=0.0)
p_met_ss = core.power_met_ss(speed_series, grade_series=None)
p_met = core.power_met(speed_series, grade_series=None, time_series=None, tau=20)
vo_2_aer_ss = core.vo_2_ss(speed_series, grade_series=None)
vo_2_aer = core.vo_2_ss(speed_series, grade_series=None, time_series=None, tau=20)
v_equiv = core.equiv_flat_speed(speed, grade=0.0)
v_flat = core.power_to_flat_speed(vo_2_aer)

### Utilities

In [ ]:
from specialsauce import util
v_sma = util.sma(v_array, window_len, time_series=None)
v_ewma = util.ewma(v_array, half_life, time_series=None)

#### Non-working example of why `pandas.df.ewm` does not do what I need it to

```python
x_series_pad = pd.concat([pd.Series([0.0]), df['tss']])
t_series_pad = pd.concat([
  pd.Series([0]).apply(pd.to_datetime, unit='s'),
  df['recorded']
])
x_avg_pad = x_series_pad.ewm(
  alpha=1/42, 
  adjust=False,
  times=t_series_pad
).mean()
x_avg_pad[1:]
```

``ewm`` says:

``NotImplementedError: times is not supported with adjust=False.``

Although the following works, as long as one workout per day:

```python
x_series_pad = pd.concat([pd.Series([0.0]), df['tss']])
x_avg_pad = df['tss'].ewm(alpha=1/42, adjust=False).mean()
x_avg_pad[1:]
```

### Old heartandsole functions (w/ proposed updates)

```python
powerutils.air_friction_coefficient(Cd, mass, proj_area, density_air_local)
powerutils.run_cost(speed, grade=None)
powerutils.run_power(speeds, grades=None)
powerutils.flat_run_power(pace)
powerutils.flat_speed(power)
```

```python
stressutils.lactate_norm(series)
stressutils.training_stress(intensity, moving_time_seconds)
```